### ISSUE TITLE
希望可以构建一个arm64版本感谢

### ISSUE THREAD

**Issue by 849165048** [FleyX/open-renamer#16]

**Comment by FleyX** [comment]
https://hub.docker.com/r/fleyx/open-renamer/tags

**Comment by 849165048** [comment]
at Module.require (node:internal/modules/cjs/loader:1005:19),
    at require (node:internal/modules/cjs/helpers:102:18),
    at Object.<anonymous> (/app/node_modules/sqlite3/lib/sqlite3-binding.js:4:15),
    at Module._compile (node:internal/modules/cjs/loader:1105:14),
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10),
    at Module.load (node:internal/modules/cjs/loader:981:32),
    at Function.Module._load (node:internal/modules/cjs/loader:822:12),
    at Module.require (node:internal/modules/cjs/loader:1005:19) {,
  code: 'MODULE_NOT_FOUND',,
  requireStack: [,
    '/app/node_modules/sqlite3/lib/sqlite3-binding.js',,
    '/app/node_modules/sqlite3/lib/sqlite3.js',,
    '/app/dist/util/SqliteHelper.js',,
    '/app/dist/index.js',
  ],
},
node:internal/modules/cjs/loader:936,
  throw err;,
  ^,
,
Error: Cannot find module '/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node',
Require stack:,
- /app/node_modules/sqlite3/lib/sqlite3-binding.js,
- /app/node_modules/sqlite3/lib/sqlite3.js,
- /app/dist/util/SqliteHelper.js,
- /app/dist/index.js,
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15),
    at Function.Module._load (node:internal/modules/cjs/loader:778:27),
    at Module.require (node:internal/modules/cjs/loader:1005:19),
    at require (node:internal/modules/cjs/helpers:102:18),
    at Object.<anonymous> (/app/node_modules/sqlite3/lib/sqlite3-binding.js:4:15),
    at Module._compile (node:internal/modules/cjs/loader:1105:14),
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10),
    at Module.load (node:internal/modules/cjs/loader:981:32),
    at Function.Module._load (node:internal/modules/cjs/loader:822:12),
    at Module.require (node:internal/modules/cjs/loader:1005:19) {,
  code: 'MODULE_NOT_FOUND',,
  requireStack: [,
    '/app/node_modules/sqlite3/lib/sqlite3-binding.js',,
    '/app/node_modules/sqlite3/lib/sqlite3.js',,
    '/app/dist/util/SqliteHelper.js',,
    '/app/dist/index.js',
  ],
},
node:internal/modules/cjs/loader:936,
  throw err;,
  ^,
,
Error: Cannot find module '/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node',
Require stack:,
- /app/node_modules/sqlite3/lib/sqlite3-binding.js,
- /app/node_modules/sqlite3/lib/sqlite3.js,
- /app/dist/util/SqliteHelper.js,
- /app/dist/index.js,
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15),
    at Function.Module._load (node:internal/modules/cjs/loader:778:27),
    at Module.require (node:internal/modules/cjs/loader:1005:19),
    at require (node:internal/modules/cjs/helpers:102:18),
    at Object.<anonymous> (/app/node_modules/sqlite3/lib/sqlite3-binding.js:4:15),
    at Module._compile (node:internal/modules/cjs/loader:1105:14),
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10),
    at Module.load (node:internal/modules/cjs/loader:981:32),
    at Function.Module._load (node:internal/modules/cjs/loader:822:12),
    at Module.require (node:internal/modules/cjs/loader:1005:19) {,
  code: 'MODULE_NOT_FOUND',,
  requireStack: [,
    '/app/node_modules/sqlite3/lib/sqlite3-binding.js',,
    '/app/node_modules/sqlite3/lib/sqlite3.js',,
    '/app/dist/util/SqliteHelper.js',,
    '/app/dist/index.js',
  ],
},
node:internal/modules/cjs/loader:936,
  throw err;,
  ^,
,
Error: Cannot find module '/app/node_modules/sqlite3/lib/binding/napi-v3-linux-arm64/node_sqlite3.node',
Require stack:,
- /app/node_modules/sqlite3/lib/sqlite3-binding.js,
- /app/node_modules/sqlite3/lib/sqlite3.js,
- /app/dist/util/SqliteHelper.js,
- /app/dist/index.js,
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15),
    at Function.Module._load (node:internal/modules/cjs/loader:778:27),
    at Module.require (node:internal/modules/cjs/loader:1005:19),
    at require (node:internal/modules/cjs/helpers:102:18),
    at Object.<anonymous> (/app/node_modules/sqlite3/lib/sqlite3-binding.js:4:15),
    at Module._compile (node:internal/modules/cjs/loader:1105:14),
    at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10),
    at Module.load (node:internal/modules/cjs/loader:981:32),
    at Function.Module._load (node:internal/modules/cjs/loader:822:12),
    at Module.require (node:internal/modules/cjs/loader:1005:19) {,
  code: 'MODULE_NOT_FOUND',,
  requireStack: [,
    '/app/node_modules/sqlite3/lib/sqlite3-binding.js',,
    '/app/node_modules/sqlite3/lib/sqlite3.js',,
    '/app/dist/util/SqliteHelper.js',,
    '/app/dist/index.js',
  ],
}

**Comment by 849165048** [comment]
不好意思才看到好像报错了

**Comment by 849165048** [comment]
如果将 openRenamerBackend/package.json  文件中修改为 "sqlite3": "^3.39.1", 则会进行以下报错

node:internal/modules/cjs/loader:936,
  throw err;,
  ^,
,
Error: Cannot find module '/app/dist/index.js',
    at Function.Module._resolveFilename (node:internal/modules/cjs/loader:933:15),
    at Function.Module._load (node:internal/modules/cjs/loader:778:27),
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:77:12),
    at node:internal/main/run_main_module:17:47 {,
  code: 'MODULE_NOT_FOUND',,
  requireStack: [],
}

**Comment by 849165048** [comment]
> 试下0.8.1版本看看，这个版本把安装依赖的操作放到镜像里去了，理论上应该可以用了

确实是可以了暂时没发现什么问题
